import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [showPosts, setshowPosts] = useState()
  const apiUrl = "https://redmine.dialedindev.ca/issues.json"
  let displayData

  async function pullRedmintask() {
    const response = await fetch(apiUrl, { 
     method: 'get', 
     headers: new Headers({
       'Authorization': 'Basic '+btoa('thangaraj.moorthi:8903833128'), 
       'Content-Type': 'application/x-www-form-urlencoded'
     })
   }
    )
    const responseData = await response.json()
    displayData = responseData.map(function(task){
      return (
        {task.issues.map((r, i) =>
          <p key={r.project.id}>{r.project.name}</p>
        )}
        )
    })
    setshowPosts(displayData)
    return
  }
  useEffect(() => {
    pullRedmintask()
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {showPosts}
      </main>
    </div>
  )
}
