import { useState, useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [showPosts, setshowPosts] = useState()
  const apiUrl = "https://jsonplaceholder.typicode.com/todos/"
  let displayData

  async function pullRedmintask() {
    const response = await fetch(apiUrl)
    const responseData = await response.json()
    displayData = responseData.map(function(tudo){
      return (
        <p key={tudo.id}>{tudo.title}</p>
        )
    })
    setshowPosts(displayData)
    return
  }
  useEffect(() => {
    pullRedmintask()
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        {showPosts}
      </main>
    </div>
  )
}
